- name: Are you sure you want to delete your cluster?
  pause: prompt='Are you sure you want to delete your cluster? Press return to continue. Press Ctrl+c and then "a" to abort'

- name: Run kubeadm reset
  shell: kubeadm reset -f
