- name: Remove swapfile from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(.+?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add docker repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add kubernetes repository key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable

- name: Add kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: Install docker
  package:
    name: docker-ce={{ docker.version }}~ce~3-0~ubuntu
    force: yes

- name: Create /etc/kubernetes folder
  file:
    path: /etc/kubernetes
    state: directory

- name: Install kubelet
  package:
    name: kubelet={{ kubernetes.version }}-00
    force: yes

- name: Install kubeadm
  package:
    name: kubeadm={{ kubernetes.version }}-00
    force: yes

- name: Enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes
