- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_node_cmd
  delegate_to: "{{ groups['k8s_master'][0] }}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_node_cmd.stdout }}"

- name: Join node through kubeadm
  shell: "{{ kubeadm_join_node_cmd }}"
