- name: Remove swapfile from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(.+?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add kubernetes repository key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: Create /etc/kubernetes folder
  file:
    path: /etc/kubernetes
    state: directory

- name: Install kubelet
  package:
    name: kubelet={{ k8s_version }}-00
    force: yes

- dpkg_selections:
    name: kubelet
    selection: hold

- name: Install kubeadm
  package:
    name: kubeadm={{ k8s_version }}-00
    force: yes

- dpkg_selections:
    name: kubeadm
    selection: hold
