- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['k8s_master'][0] }}"

- set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"

- name: Join through kubeadm
  shell: "{{ kubeadm_join }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt

- name: Chmod 0600 ~/node_joined.txt
  file:
    path: ~/node_joined.txt
    mode: 0600
