- name: apply role k8s-common
  hosts:
    - k8s_master
    - k8s_node
  roles:
    - k8s-common

- name: apply role k8s-master
  hosts: k8s_master
  roles:
    - k8s-master

- name: apply role k8s-node
  hosts: k8s_node
  roles:
    - k8s-node
